version: '3.8'

services:
  echo-server:
    build: .
    container_name: echo-controller
    ports:
      - "443:443"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  default:
    name: echo-network